#!/usr/bin/env python3
"""check_network_freshness.py — how many days behind reality is the warm-network data?

WHY THIS EXISTS. The pipeline is only as fresh as the last MANUAL LinkedIn export, and nothing
measured that. Connections made after the last export exist in NO file: not warm-network.md, not the
warm-rung roster anchor the send gate reads, not the daily briefing, not the closeness store. The gap
widens silently and the only symptom is a daily "3 people" pick that quietly stops including anyone
recent.

TWO DIFFERENT STALENESS PROBLEMS, TWO DIFFERENT FIXES, AND THE MESSAGE MUST SAY WHICH:

  • The PARSE is behind an export already on disk  → re-run `parse_network.py`. Cheap, no human.
  • The newest EXPORT on disk is itself old        → only you can fix it, by downloading a fresh
                                                     export from LinkedIn. No script can.

Reporting one number would collapse those into an unactionable "it's stale". A check that cannot
tell you what to do next is a check that gets ignored, which is the failure mode this file ends.

Usage:  scripts/check_network_freshness.py [--warn-days 7] [--fail-days 14] [--quiet]
Exit:   0 = current · 1 = behind, re-parse will fix it · 2 = the export itself is stale, human needed
        3 = usage / unreadable
"""
import json
import os
import re
import sys
from datetime import date, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.environ.get("CLAUDE_PROJECT_DIR") or os.path.dirname(HERE)

WARN_DAYS_DEFAULT = 7
FAIL_DAYS_DEFAULT = 14

# `| 39 | Name | Title | Company | 🟡 1y (2025-03-07) | ✉ |` — the date inside the Known-since cell.
# Keyed on the PARENTHESISED DATE, never on the emoji: the same three badges mean different things
# in different tables of this file, so logic reads text and never a glyph.
_CONNECTED_ON = re.compile(r"\((\d{4}-\d{2}-\d{2})\)")
# The header records which export produced the file:
#   > Generated by `scripts/parse_network.py` from `…_07-21-2026.zip.zip::Connections.csv`.
_SOURCE_LINE = re.compile(r"Generated by .*?from `([^`]+)`")


def newest_connection(path=None):
    """Newest `Connected On` date present in warm-network.md, or None."""
    path = path or os.path.join(REPO, "documents", "warm-network.md")
    try:
        text = open(path, encoding="utf-8", errors="ignore").read()
    except Exception:
        return None
    found = _CONNECTED_ON.findall(text)
    if not found:
        return None
    try:
        return max(date.fromisoformat(d) for d in found)
    except Exception:
        return None


def recorded_source(path=None):
    """The export the current warm-network.md was generated from, per its own header."""
    path = path or os.path.join(REPO, "documents", "warm-network.md")
    try:
        m = _SOURCE_LINE.search(open(path, encoding="utf-8", errors="ignore").read())
    except Exception:
        return None
    return m.group(1) if m else None


def newest_export_connection():
    """(newest Connected On INSIDE the resolved export, its path). Reuses parse_network.

    ⚠️ COMPARE CONNECTION DATES TO CONNECTION DATES. The first cut of this file compared the
    export's FILENAME date against the newest parsed connection and concluded "you are behind an
    export on disk, just re-parse". That is wrong and actively misleading: an export is dated when
    it was TAKEN, which is always later than the newest connection inside it. The check would then
    prescribe a re-parse every single day, and the re-parse would gain nothing.

    A check that confidently prescribes a no-op is worse than no check, because it trains the
    operator to ignore it.
    """
    sys.path.insert(0, HERE)
    try:
        from parse_network import find_export, parse_rows, connected_on
    except Exception:
        return None, None
    try:
        path, text = find_export()
        if not text:
            return None, path
        dates = [connected_on(r.get("Connected On")) for r in parse_rows(text)]
        dates = [d for d in dates if d]
        return (max(dates) if dates else None), path
    except Exception:
        return None, None


def _store_coverage():
    """LIVE closeness-store coverage, computed from the two sources every time.

    The two sources are the export on disk (the contact universe) and the store's own contents
    (who has an answer). A `_last_swept_export` stamp may exist in the store — it is surfaced as
    provenance, but every NUMBER here is recomputed, so this check can never claim a freshness the
    sources do not support. Returns {} keys defaulted when either source is missing."""
    out = {"store_present": False, "store_rows": 0, "store_stated": 0, "store_unswept": None,
           "store_last_swept_export": None}
    try:
        raw = json.load(open(os.path.join(REPO, "documents", "contact-closeness.json"),
                             encoding="utf-8"))
    except Exception:
        return out
    out["store_present"] = True
    contacts = {k: v for k, v in (raw.get("contacts") or {}).items() if isinstance(v, dict)}
    out["store_rows"] = len(contacts)
    out["store_last_swept_export"] = raw.get("_last_swept_export")
    sys.path.insert(0, HERE)
    try:
        import closeness
        out["store_stated"] = sum(
            1 for r in contacts.values()
            if r.get("closeness") and str(r.get("source") or "") not in closeness.INFERRED_SOURCES)
        # Unswept = export contacts with NO recorded closeness at all, matched on the normalized
        # entity like every other consumer of this store.
        from parse_network import find_export, parse_rows
        _p, text = find_export()
        if text:
            levelled = {closeness.normalize_name(k) for k, r in contacts.items()
                        if r.get("closeness")}
            names = {closeness.normalize_name(
                f"{(r.get('First Name') or '').strip()} {(r.get('Last Name') or '').strip()}")
                for r in parse_rows(text)}
            names.discard("")
            out["store_unswept"] = len(names - levelled)
    except Exception:
        pass
    return out


def scan(today=None):
    """Pure scan. Returns a dict; prints nothing. consistency-check step [18] calls this.

    Store-coverage keys are ADDITIVE (2026-07-27): existing consumers (session_start, the
    consistency check) keep reading the original keys unchanged."""
    today = today or date.today()
    newest = newest_connection()
    exp_newest, exp_path = newest_export_connection()
    out = {
        "today": today,
        "newest_connection": newest,
        "data_lag_days": (today - newest).days if newest else None,
        "export_newest_connection": exp_newest,
        "export_path": exp_path,
        "export_lag_days": (today - exp_newest).days if exp_newest else None,
        "parse_is_behind_export": bool(newest and exp_newest and exp_newest > newest),
        "source": recorded_source(),
    }
    out.update(_store_coverage())
    return out


def main():
    args = sys.argv[1:]

    def _opt(flag, default):
        if flag in args:
            i = args.index(flag)
            if i + 1 < len(args):
                try:
                    return int(args[i + 1])
                except ValueError:
                    pass
            print(f"usage: check_network_freshness.py [{flag} N]")
            sys.exit(3)
        return default

    warn_days = _opt("--warn-days", WARN_DAYS_DEFAULT)
    fail_days = _opt("--fail-days", FAIL_DAYS_DEFAULT)
    quiet = "--quiet" in args

    s = scan()
    if s["newest_connection"] is None:
        # No data at all is a fresh install, so the EXIT stays 0 — but on this kit that silence
        # WAS the defect: nothing ever told the operator to produce the one input the warm rungs
        # run on. Pass quietly in code, prompt loudly in text.
        if not quiet:
            print("🟠 NO network data yet — the pipeline is running blind on relationships.")
            print("   The warm rungs (5-7) stay locked until you level your network. Three steps:")
            print("   1. LinkedIn → Settings → Data privacy → 'Get a copy of your data' → request it")
            print("   2. Drop the .zip in your Downloads folder")
            print("   3. In Claude Code run: /level-network  (ingests it, infers what it can, then")
            print("      asks you about the rest in short batches — stop and resume any time)")
        return 0

    lag = s["data_lag_days"]
    lines = [f"newest connection on file: {s['newest_connection']} ({lag}d ago)"]
    if s["export_newest_connection"]:
        lines.append(f"newest in export on disk:  {s['export_newest_connection']} "
                     f"({s['export_lag_days']}d ago) · {os.path.basename(s['export_path'] or '')}")
    # Closeness coverage, recomputed live from the two sources (see _store_coverage).
    if s["store_present"]:
        cov = (f"closeness store: {s['store_rows']} rows · {s['store_stated']} stated by you"
               + (f" · {s['store_unswept']} unswept" if s["store_unswept"] is not None else ""))
        lines.append(cov)
        if s["store_unswept"]:
            lines.append("   level the rest: /level-network (resumes where you left off)")
    else:
        lines.append("closeness store: ABSENT — warm rungs locked; run /level-network to create it")

    # A re-parse can only help when disk actually holds something newer than the parse.
    if s["parse_is_behind_export"]:
        code = 1
        head = (f"🟠 warm-network is BEHIND an export already on disk "
                f"({s['newest_connection']} parsed vs {s['export_newest_connection']} available)")
        fix = "   fix: python3 scripts/parse_network.py    (no download needed)"
    elif lag >= fail_days:
        code = 2
        head = f"🔴 warm-network data is {lag} days old and no newer export exists on disk"
        fix = ("   fix: download a fresh LinkedIn export (Settings → Data privacy → Get a copy of "
               "your data), then run python3 scripts/parse_network.py")
    elif lag >= warn_days:
        code = 1
        head = f"🟠 warm-network data is {lag} days old (warn at {warn_days}, hard at {fail_days})"
        fix = ("   fix: download a fresh LinkedIn export, then run "
               "python3 scripts/parse_network.py")
    else:
        code = 0
        head = f"✅ warm-network data is current ({lag}d)"
        fix = None

    if not quiet:
        print(head)
        for line in lines:
            print(f"   {line}")
        if fix:
            print(fix)
            print("   ⚠️  every connection made after the newest date above is invisible to the "
                  "daily 3-3-3, the warm-rung roster anchor, and check_dup.")
    return code


if __name__ == "__main__":
    sys.exit(main())
