#!/usr/bin/env bash
# daily-rank.sh — re-rank the board and the people pool every morning, on CURRENT data.
#
# WHY. The operator's framing upstream, 2026-08-10: *"we should always be working with the current
# data."* The roster is the
# input to every people decision and it drifts silently. On the day this was written the parse sat
# 15 days behind an export already sitting on disk, 35 connections were invisible to the daily
# 3-3-3, and `check_network_freshness.py` had been printing a correct warning the whole time that
# nothing acted on.
#
# ⚖️ AUTO-PARSE, THEN REPORT (his ruling, not a blocking gate). A fresher export on disk gets parsed
# without asking, because re-parsing is cheap, reversible and needs no human. What CANNOT be
# self-healed is a stale export: only he can download one, so that raises a briefing item instead.
#
# Runs BEFORE the 08:00 attractor prep so the morning 3-3-3 reads fresh rankings.
# Conventions copied from auto-sweep.sh: absolute PROJECT, explicit PATH (launchd's is minimal),
# append-with-banner logging, dated markdown output, NO commit (the 21:00 backup collects it).
set -uo pipefail

PROJECT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
export PATH="${JOBKIT_PATH:-/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin}"
cd "$PROJECT" || exit 1

LOG="documents/daily-rank.log"
TODAY="$(date '+%Y-%m-%d')"
OUT="documents/daily-rank-$TODAY.md"
exec >> "$LOG" 2>&1
echo "===== DAILY-RANK $(date '+%Y-%m-%d %H:%M:%S %Z') ====="

# ── 1. FRESHNESS, and the two outcomes are different problems ────────────────────────────────
# exit 1 = the parse is behind an export on disk  → fix it here, no human needed.
# exit 2 = the newest export is itself old        → only a download clears it; say so and continue.
python3 scripts/check_network_freshness.py --quiet
FRESH=$?
if [ "$FRESH" -eq 1 ]; then
  echo "→ parse is behind an export on disk; parsing (auto-parse ruling 2026-08-10)"
  python3 scripts/reconcile_contacts.py --apply --quiet || true
  # ⛔ RE-CHECK. Do not announce a repair you have not confirmed. The first run of this job
  # (2026-08-10) printed "→ re-parsed" against a condition the re-parse could not clear, because
  # the freshness check was reading a proxy. A self-heal that cannot verify itself is a job that
  # reports success every morning while the thing it heals stays broken.
  python3 scripts/check_network_freshness.py --quiet
  if [ $? -eq 1 ]; then
    echo "🔴 the re-parse did NOT clear it. The parse is still behind the export on disk."
    echo "   That is a DEFECT in the parse or the check, not a stale download. Do not re-run;"
    echo "   run scripts/check_network_freshness.py by hand and read what it compares."
  else
    echo "→ re-parsed and VERIFIED clear. what changed is in the reconcile report for today."
  fi
elif [ "$FRESH" -eq 2 ]; then
  echo "⚠️  the EXPORT ITSELF is stale. No script can fix this; it needs a fresh download."
fi

# ── 2. ABORT FLOOR. A collapsed roster must fail loudly, not rank quietly. ────────────────────
# auto-sweep.sh's lesson: a run that produces almost nothing looks like a tidy success. A roster
# that suddenly holds a handful of people means the parse or the export broke, and ranking it would
# hand the operator a confident, tiny, wrong pick list.
ROSTER_N="$(grep -c '(20[0-9][0-9]-[0-9][0-9]-[0-9][0-9])' documents/warm-network.md 2>/dev/null || echo 0)"
if [ "$ROSTER_N" -lt 200 ]; then
  # ⚠️ ~800, not ~1400. The export holds 1,447 people; only those who RANK into one of the four
  # sections get a dated row, and the rest land in the undated full-roster list. The old message
  # said "expected ~1400+" against a file that has never held that, so anyone hitting this abort
  # would have read a healthy roster as broken. Same proxy confusion as BUG-146, one file over.
  echo "🔴 ABORT: warm-network.md holds only $ROSTER_N dated rows (expected ~800)."
  echo "   The ROSTER is broken, not the market. Not ranking against it."
  echo "===== END (exit 1) ====="
  exit 1
fi

# ── 3. RANK, both pools ──────────────────────────────────────────────────────────────────────
{
  echo "# Daily rank — $TODAY"
  echo
  echo "> Regenerated by \`scripts/daily-rank.sh\`. Companies by the criteria matrix, people by"
  echo "> relationship distance and who can help first. Re-run any time; this file is disposable."
  echo
  echo '## Companies'
  echo '```'
  python3 scripts/rank_criteria.py 2>/dev/null | head -60
  echo '```'
  echo
  echo '## People'
  echo '```'
  python3 scripts/rank_criteria.py --pool people --n 10 2>/dev/null | head -50
  echo '```'
} > "$OUT"
echo "→ wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines, $ROSTER_N dated roster rows)"

# ── 4. STAMP, so a job that stops running becomes visible ────────────────────────────────────
# A launchd job that is LOADED is not a job that RAN. durability-check.sh can only see the former,
# so the stamp is what lets session_start notice silence.
python3 - <<'PY'
import json, os
from datetime import datetime, timezone
p = os.path.join("documents", "state", "daily-rank.json")
os.makedirs(os.path.dirname(p), exist_ok=True)
json.dump({"last_run": datetime.now(timezone.utc).isoformat(timespec="seconds")},
          open(p, "w"), indent=2)
PY

echo "===== END (exit $?) ====="
